/**
 * @script process-report.ts
 * @description Post-processes the Mochawesome JSON report generated after a Cypress run.
 *              It copies screenshot files from `cypress/screenshots/` into
 *              `cypress/reports/html/screenshots/` and rewrites their paths inside
 *              `cypress/reports/mochawesome.json` so the HTML report renders them correctly.
 *
 *              This script is intended to be run automatically as part of the report
 *              pipeline (e.g. via `npm run report`) after `cypress run` completes.
 *
 * @usage
 *   npx ts-node scripts/process-report.ts
 *   npm run report          (typically invoked as a step within the report npm script)
 *
 * @arguments
 *   None.
 *
 * @prerequisites
 *   - `cypress/reports/mochawesome.json` must exist (generated by cypress-mochawesome-reporter).
 *   - Screenshots (if any) must be present under `cypress/screenshots/`.
 *
 * @output
 *   Prints "Screenshots copied and paths updated in report JSON." on success.
 *
 * @sideEffects
 *   - Copies screenshot files to cypress/reports/html/screenshots/.
 *   - Overwrites cypress/reports/mochawesome.json with updated screenshot paths.
 */
import fs from 'fs';
import path from 'path';

const projectRoot = path.resolve(__dirname, '..');
const jsonPath = path.join(projectRoot, 'cypress/reports/mochawesome.json');
const screenshotsSrc = path.join(projectRoot, 'cypress/screenshots');
const screenshotsDest = path.join(projectRoot, 'cypress/reports/html/screenshots');

function copyFile(src: string, dest: string): void {
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.copyFileSync(src, dest);
}

function processContext(contextStr: string | undefined): string | undefined {
  if (!contextStr) return contextStr;
  try {
    const ctx = JSON.parse(contextStr);
    if (
      ctx.title === 'cypress-mochawesome-reporter-screenshots' &&
      Array.isArray(ctx.value)
    ) {
      ctx.value = ctx.value.map((pair: unknown) => {
        if (!Array.isArray(pair)) return pair;
        return (pair as string[]).map((relPath) => {
          const normalized = relPath.replace(/\\/g, '/').replace(/^\//, '');
          const srcFile = path.join(screenshotsSrc, normalized);
          const destFile = path.join(screenshotsDest, normalized);
          if (fs.existsSync(srcFile)) {
            copyFile(srcFile, destFile);
          }
          return 'screenshots/' + normalized;
        });
      });
      return JSON.stringify(ctx);
    }
  } catch (_e) {}
  return contextStr;
}

interface MochawesomeTest {
  context?: string;
}

interface MochawesomeSuite {
  tests?: MochawesomeTest[];
  suites?: MochawesomeSuite[];
}

interface MochawesomeResult {
  suites?: MochawesomeSuite[];
}

interface MochawesomeStats {
  passPercent?: number | null;
  pendingPercent?: number | null;
  [key: string]: unknown;
}

interface MochawesomeReport {
  stats?: MochawesomeStats;
  results: MochawesomeResult[];
}

function processTests(tests: MochawesomeTest[] | undefined): void {
  if (!tests) return;
  tests.forEach((test) => {
    if (test.context) test.context = processContext(test.context);
  });
}

function processSuites(suites: MochawesomeSuite[] | undefined): void {
  if (!suites) return;
  suites.forEach((suite) => {
    processTests(suite.tests);
    processSuites(suite.suites);
  });
}

const json: MochawesomeReport = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
json.results.forEach((result) => processSuites(result.suites));

if (json.stats) {
  if (json.stats.passPercent == null) json.stats.passPercent = 0;
  if (json.stats.pendingPercent == null) json.stats.pendingPercent = 0;
}

fs.writeFileSync(jsonPath, JSON.stringify(json, null, 2));
console.log('Screenshots copied and paths updated in report JSON.');
